### ISSUE TITLE
POW! Angel initativ (crowdfunding)

### ISSUE THREAD

**Issue by raae** [raae/pow-app#34]
- [ ] Copy for the page #42 
- [ ] Social media plan and snippets/images
- [x] Page with stripe checkout #36 
- [x] Seperate angel checkout content from code #48
- [x] Get spots left from stripe #47

We'll manually add them to a newsletter or just use Gmail to communicate with them. Maximum of 33 people.
