### ISSUE TITLE
Epic: Set Up Payment for Donations to POW! with Stripe Checkout

### ISSUE THREAD

**Issue by olavea** [raae/pow-app#39]
Deadline Wednesday, Nov 6th.
More thoughts about POW! Angels can be found in #34.

To get started:

- [x]  Clone repository git clone git@github.com:raae/pow-app.git
- [x]  Create a branch git checkout -b angels-#36
- [ ] Change from "live" to "test" API keys
- [ ] Change from "Plans" to "Products" API keys
- [ ] 
- [ ] 

The task

- [ ]  Create a page where the user can choose between three different Stripe SKUs (gold, silver, bronze) and pay.

- [ ]  Create a page in the pages directory, a js page. Not a md page at this point. Do not think about design or copy at this point, the page should look like this:

![Uploading 1_year_of_POW-tegning-10.jpg…]()

- [ ]  Create a Checkout component that takes a product id as a prop, so you can reuse it for the three products.  slik at du ikke må lage checkout1, checkout2, checkout3.
- [ ]  Try to make it functional with hooks.
- [ ]  RemoveComponentDidMount use React Hooks
