### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by raae** [raae/pow-app#75]
Create an onboarding flow.

- [x] Create account
- [x] Collect initial cycle data #76 
- [x] Short explanation of the hashtag concept and get main hashtag #78 
- [x] Redirect to Stripe for payment #69
